@SmartAgentApi_HostAddress = https://localhost:7274

GET {{SmartAgentApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{SmartAgentApi_HostAddress}}/dicompack

###

@checkKey=66289592976114364271748871
GET {{SmartAgentApi_HostAddress}}/dicompack/CheckResult/{{checkKey}}

###

GET {{SmartAgentApi_HostAddress}}/dicompack/Download/{{checkKey}}

###

GET {{SmartAgentApi_HostAddress}}/dicompack/CheckResult/{{checkKey}}

###
